### ISSUE TITLE
Linking models

### ISSUE THREAD

**Issue by rickhall** [RyanSusana/elepy#40] opened 2019-03-26 16:38 UTC
Admittedly, I didn't spend a ton of time scouring the docs, but I didn't see how you'd go about linking models together whether it be for something like you might want for implementing line items on an order or some sort of hierarchical categorization mechanism. Am I missing something obvious?

Would I just manually search for related models using IDs?

**Comment by RyanSusana** [comment] 2019-03-26 17:36
Hi @rickhall.
The core supports Lists of objects and Inner objects, 

The CMS, however, does.

I am looking for  a creative way to display/edit lists of objects or referred models.

**Comment by RyanSusana** [comment] 2019-03-26 17:37
Any ideas?

**Comment by rickhall** [comment] 2019-03-26 17:45
Did you mean, "The CMS, however, does **not**." ?

I don't have any brilliant ideas, I just expected to see some sort of field annotation for relationships.

**Comment by rickhall** [comment] 2019-03-26 17:49
I guess I'd be happy with even a slightly more complex example that shows best practice approach for even achieving relationships in Elepy.

**Comment by RyanSusana** [comment] 2019-03-26 17:56
Yeah my bad, that's what I meant haha. Right now I'm looking for a way to implement this and keep it database agnostic. Maybe the same way JPA does it.

My problem is displaying it in the CMS in a generic way. If I have an order, how would I handle order lines.

What you can do for now is override the CMS view with your custom domain. 
I will look at adding  @OneToOne, @OneToMany and  @ManyToOne annotations.

**Comment by RyanSusana** [comment] 2019-03-26 17:56
Thank you for the feedback though!

**Comment by rickhall** [comment] 2019-03-26 19:06
No problem.

I'm looking into options to avoid rolling my own CMS too. The main features I need, besides your basic models, is a way to relate models and a way to create a hierarchical model(s) that I can use as categorization schemes for organizing other primary models. Nothing too fancy.

Keep up the good work. I'll keep an eye on it and try to play around with it. Thanks.

**Comment by RyanSusana** [comment] 2019-03-26 19:31
You can have inner objects.

The CMS supports inner objects 1 deep.

**Comment by RyanSusana** [comment] 2019-03-26 19:32
I still don't know a good way to display it more than 1 deep generically. But you can use a custom view for that ;)

**Comment by RyanSusana** [comment] 2019-04-09 19:43
So the idea to solve the problem is `@Reference(to = ModelClass)` and `@ListOfReferences(to = ModelClass)`

I am working on the new Vue Frontend, you can find it here: https://github.com/RyanSusana/elepy-vue

**Comment by RyanSusana** [comment] 2019-08-02 06:20
The groundwork has been set for this @rickhall will be released in v2.1.0.

Thanks!

**Comment by furbykk** [comment] 2019-10-24 10:51
I think i am looking for the same solution, is this done in some version?

**Comment by RyanSusana** [comment] 2020-03-17 01:58
Hi, this has been implemented

in v3.0.0-alpha-6

Docs soon

**Closed by RyanSusana** 2020-03-17 01:58 UTC
Labels: enhancement, version 2

**Comment by aman1064** [comment] 2020-12-08 18:00
@RyanSusana  can you create an example of how to use this? Maybe a sample project?

**Comment by aman1064** [comment] 2020-12-12 14:14
> Hi, this has been implemented
> 
> in v3.0.0-alpha-6
> 
> Docs soon

Can you create a sample project on how to use this. Or may be a document it

**Comment by RyanSusana** [comment] 2020-12-13 23:53
Hi @aman1064,

Right now I'm working towards some examples.

You can use the `@Reference(to = TheOtherModel.class)` on a field where the type is the ID type of TheOtherModel.class
